# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e4e3b9a0c70202c5c18af136cf2e988aac4c8ea9c2031a4599c02217632afcd0c16061204f268377f7f51d8e414824a55f7d3e74b352fa0fa6d1615b0d9c8ee

test:
  secret_key_base: 2d7087e8a75f0acf9cffd3df90fe204f81978f1fb20551b5f9efce2cb10afa1a52722e900d2a464096d8858ad7e4c64bd3773920a197b6b3c6526f2a5f087a62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
